// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Store = require("svelte/store");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Svelte = {};

var $$Response = {};

var count = Store.writable(0);

var randomNumber = Store.writable(0);

var errorMessage = Store.writable("");

function parser(value) {
  if (value !== undefined) {
    return Caml_option.valFromOption(value).json();
  } else {
    return Promise.resolve("Something went wrong");
  }
}

function randomNumberAPI(param) {
  var __x = fetch("https://svelte.dev/tutorial/random-number");
  return __x.then(function (value) {
              console.log(value);
              return Promise.resolve(value);
            });
}

function fetchRandomNumber(param) {
  var __x = randomNumberAPI(undefined);
  var __x$1 = __x.then(parser);
  return __x$1.then(function (body) {
              console.log(body);
              return Promise.resolve(body);
            });
}

var APIException = /* @__PURE__ */Caml_exceptions.create("App-SvelteWithRescript.APIException");

function generateRandomNumber(param) {
  var __x = fetchRandomNumber(undefined);
  var __x$1 = __x.then(function (data) {
        var data$1 = Belt_Int.fromString(data);
        var newRandNumber;
        if (data$1 !== undefined) {
          newRandNumber = data$1;
        } else {
          throw {
                RE_EXN_ID: APIException,
                _1: data,
                Error: new Error()
              };
        }
        Curry._1(errorMessage.update, (function (param) {
                return "";
              }));
        Curry._1(randomNumber.update, (function (param) {
                return newRandNumber;
              }));
        return Promise.resolve(true);
      });
  return __x$1.catch(function (param) {
              Curry._1(randomNumber.update, (function (param) {
                      return 0;
                    }));
              Curry._1(errorMessage.update, (function (param) {
                      return "The random number generator api is currently having a problem!";
                    }));
              return Promise.resolve(false);
            });
}

function incrementCount(param) {
  console.log("calling -- incrementCount()");
  return Curry._1(count.update, (function (value) {
                return value + 1 | 0;
              }));
}

function decrementCount(param) {
  console.log("calling -- decrementCount()");
  return Curry._1(count.update, (function (value) {
                return value - 1 | 0;
              }));
}

exports.Svelte = Svelte;
exports.$$Response = $$Response;
exports.count = count;
exports.randomNumber = randomNumber;
exports.errorMessage = errorMessage;
exports.parser = parser;
exports.randomNumberAPI = randomNumberAPI;
exports.fetchRandomNumber = fetchRandomNumber;
exports.APIException = APIException;
exports.generateRandomNumber = generateRandomNumber;
exports.incrementCount = incrementCount;
exports.decrementCount = decrementCount;
/* count Not a pure module */
